window.BILLING_SITE_CONFIG = {
  organizationName: "García Vidal Contaduría y Auditoría",
  organizationShortName: "García Vidal",
  organizationTagline: "Contaduría y Auditoría",
  logoBrand: "GARCÍA VIDAL",
  logoTagline: "CONTADURÍA Y AUDITORÍA",
  productTagline: "Contaduría y Auditoría · El Salvador",
  footerBrandText: "García Vidal — Contaduría y Auditoría · San Salvador, El Salvador",
  heroProofLead: "Aprobado y utilizado por profesionales.",
  heroProofText: "García Vidal — Contaduría y Auditoría cierra los meses de sus clientes con BillingAgent: es nuestra herramienta de trabajo diaria.",
  siteUrl: "https://billagentbygv.github.io/",
  contactEmail: "garciavidalcya@gmail.com",
  contactSubject: "Quiero información de BillingAgent",
  contactFormUrl: "https://formsubmit.co/garciavidalcya@gmail.com",
  contactPageUrl: "https://billagentbygv.github.io/#contacto",
  instagramUrl: "https://www.instagram.com/garciavidalc.a",
  tiktokUrl: "https://www.tiktok.com/@firma.garcia.vida",
  // Precios — única fuente de verdad. El HTML visible los toma de aquí;
  // validate_site_config.py exige que el JSON-LD (index.html) y llms.txt coincidan.
  pricingProgram1Name: "1 correo",
  pricingProgram1Price: "$250",
  pricingProgram1SubMonthly: "$40",
  pricingProgram1SubQuarterly: "$100",
  pricingProgram1SubSave: "Ahorrás $20",
  pricingProgram3Name: "Hasta 3 correos",
  pricingProgram3Price: "$375",
  pricingProgram3SubMonthly: "$50",
  pricingProgram3SubQuarterly: "$120",
  pricingProgram3SubSave: "Ahorrás $30",
  pricingQuoteLabel: "Precio a tu medida",
};
